<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "clients".
 *
 * @property integer $id
 * @property integer $client_code
 * @property string $name
 *
 * @property \app\models\ClientsAccounts[] $clientsAccounts
 * @property \app\models\SellingBills[] $sellingBills
 * @property string $aliasModel
 */
abstract class Clients extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'clients';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['client_code'], 'integer'],
            [['name'], 'string', 'max' => 500]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'client_code' => 'Client Code',
            'name' => 'Name',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClientsAccounts()
    {
        return $this->hasMany(\app\models\ClientsAccounts::className(), ['clients_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSellingBills()
    {
        return $this->hasMany(\app\models\SellingBills::className(), ['clients_id' => 'id']);
    }




}
