<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "clients_accounts".
 *
 * @property integer $id
 * @property integer $clients_id
 * @property string $dept
 * @property string $credit
 *
 * @property \app\models\Clients $clients
 * @property string $aliasModel
 */
abstract class ClientsAccounts extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'clients_accounts';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['clients_id'], 'integer'],
            [['dept', 'credit'], 'number'],
            [['clients_id'], 'exist', 'skipOnError' => true, 'targetClass' => Clients::className(), 'targetAttribute' => ['clients_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'clients_id' => 'Clients ID',
            'dept' => 'Dept',
            'credit' => 'Credit',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClients()
    {
        return $this->hasOne(\app\models\Clients::className(), ['id' => 'clients_id']);
    }




}
