<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "purchasing_bills".
 *
 * @property integer $id
 * @property integer $suppliers_id
 * @property integer $bill_code
 * @property string $total_cost
 * @property string $total_discount
 * @property string $date
 *
 * @property \app\models\Suppliers $suppliers
 * @property \app\models\PurchasingBillsDetails[] $purchasingBillsDetails
 * @property string $aliasModel
 */
abstract class PurchasingBills extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'purchasing_bills';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['suppliers_id', 'bill_code'], 'integer'],
            [['total_cost', 'total_discount'], 'number'],
            [['date'], 'safe'],
            [['suppliers_id'], 'exist', 'skipOnError' => true, 'targetClass' => Suppliers::className(), 'targetAttribute' => ['suppliers_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'suppliers_id' => 'Suppliers ID',
            'bill_code' => 'Bill Code',
            'total_cost' => 'Total Cost',
            'total_discount' => 'Total Discount',
            'date' => 'Date',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSuppliers()
    {
        return $this->hasOne(\app\models\Suppliers::className(), ['id' => 'suppliers_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPurchasingBillsDetails()
    {
        return $this->hasMany(\app\models\PurchasingBillsDetails::className(), ['purchasing_bills_id' => 'id']);
    }




}
