<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "purchasing_bills_details".
 *
 * @property integer $id
 * @property integer $purchasing_bills_id
 * @property integer $items_id
 * @property integer $quantity
 * @property string $cost
 *
 * @property \app\models\Items $items
 * @property \app\models\PurchasingBills $purchasingBills
 * @property string $aliasModel
 */
abstract class PurchasingBillsDetails extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'purchasing_bills_details';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['purchasing_bills_id', 'items_id', 'quantity'], 'integer'],
            [['cost'], 'number'],
            [['items_id'], 'exist', 'skipOnError' => true, 'targetClass' => Items::className(), 'targetAttribute' => ['items_id' => 'id']],
            [['purchasing_bills_id'], 'exist', 'skipOnError' => true, 'targetClass' => PurchasingBills::className(), 'targetAttribute' => ['purchasing_bills_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'purchasing_bills_id' => 'Purchasing Bills ID',
            'items_id' => 'Items ID',
            'quantity' => 'Quantity',
            'cost' => 'Cost',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItems()
    {
        return $this->hasOne(\app\models\Items::className(), ['id' => 'items_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPurchasingBills()
    {
        return $this->hasOne(\app\models\PurchasingBills::className(), ['id' => 'purchasing_bills_id']);
    }




}
