<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "selling_bills_details".
 *
 * @property integer $id
 * @property integer $selling_bills_id
 * @property integer $items_id
 * @property integer $quantity
 * @property string $price
 *
 * @property \app\models\Items $items
 * @property \app\models\SellingBills $sellingBills
 * @property string $aliasModel
 */
abstract class SellingBillsDetails extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'selling_bills_details';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['selling_bills_id', 'items_id', 'quantity'], 'integer'],
            [['price'], 'number'],
            [['items_id'], 'exist', 'skipOnError' => true, 'targetClass' => Items::className(), 'targetAttribute' => ['items_id' => 'id']],
            [['selling_bills_id'], 'exist', 'skipOnError' => true, 'targetClass' => SellingBills::className(), 'targetAttribute' => ['selling_bills_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'selling_bills_id' => 'Selling Bills ID',
            'items_id' => 'Items ID',
            'quantity' => 'Quantity',
            'price' => 'Price',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItems()
    {
        return $this->hasOne(\app\models\Items::className(), ['id' => 'items_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSellingBills()
    {
        return $this->hasOne(\app\models\SellingBills::className(), ['id' => 'selling_bills_id']);
    }




}
