<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "sub_units".
 *
 * @property integer $id
 * @property integer $units_id
 * @property integer $main_unit_id
 * @property integer $main_unit_quantity
 *
 * @property \app\models\MainUnits $mainUnit
 * @property \app\models\Units $units
 * @property string $aliasModel
 */
abstract class SubUnits extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sub_units';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['units_id', 'main_unit_id', 'main_unit_quantity'], 'integer'],
            [['main_unit_id'], 'exist', 'skipOnError' => true, 'targetClass' => MainUnits::className(), 'targetAttribute' => ['main_unit_id' => 'id']],
            [['units_id'], 'exist', 'skipOnError' => true, 'targetClass' => Units::className(), 'targetAttribute' => ['units_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'units_id' => 'Units ID',
            'main_unit_id' => 'Main Unit ID',
            'main_unit_quantity' => 'Main Unit Quantity',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMainUnit()
    {
        return $this->hasOne(\app\models\MainUnits::className(), ['id' => 'main_unit_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUnits()
    {
        return $this->hasOne(\app\models\Units::className(), ['id' => 'units_id']);
    }




}
