<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "suppliers_accounts".
 *
 * @property integer $id
 * @property integer $suppliers_id
 * @property string $dept
 * @property string $credit
 *
 * @property \app\models\Suppliers $suppliers
 * @property string $aliasModel
 */
abstract class SuppliersAccounts extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'suppliers_accounts';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['suppliers_id'], 'integer'],
            [['dept', 'credit'], 'number'],
            [['suppliers_id'], 'exist', 'skipOnError' => true, 'targetClass' => Suppliers::className(), 'targetAttribute' => ['suppliers_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'suppliers_id' => 'Suppliers ID',
            'dept' => 'Dept',
            'credit' => 'Credit',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSuppliers()
    {
        return $this->hasOne(\app\models\Suppliers::className(), ['id' => 'suppliers_id']);
    }




}
