<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "suppliers".
 *
 * @property integer $id
 * @property integer $supplier_code
 * @property string $name
 * @property string $Address
 * @property string $company
 *
 * @property \app\models\PurchasingBills[] $purchasingBills
 * @property \app\models\SuppliersAccounts[] $suppliersAccounts
 * @property string $aliasModel
 */
abstract class Suppliers extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'suppliers';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['supplier_code'], 'integer'],
            [['Address'], 'string'],
            [['name'], 'string', 'max' => 500],
            [['company'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'supplier_code' => 'Supplier Code',
            'name' => 'Name',
            'Address' => 'Address',
            'company' => 'Company',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPurchasingBills()
    {
        return $this->hasMany(\app\models\PurchasingBills::className(), ['suppliers_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSuppliersAccounts()
    {
        return $this->hasMany(\app\models\SuppliersAccounts::className(), ['suppliers_id' => 'id']);
    }




}
