<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "units".
 *
 * @property integer $id
 * @property string $unit_name
 *
 * @property \app\models\MainUnits[] $mainUnits
 * @property \app\models\SubUnits[] $subUnits
 * @property string $aliasModel
 */
abstract class Units extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'units';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['unit_name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'unit_name' => 'Unit Name',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMainUnits()
    {
        return $this->hasMany(\app\models\MainUnits::className(), ['units_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubUnits()
    {
        return $this->hasMany(\app\models\SubUnits::className(), ['units_id' => 'id']);
    }




}
